"""TASK-030 structural contracts and migration-assessment foundations."""

from paperworks.contracts.legacy_adapter import (
    ADAPTER_VERSION,
    assess_legacy_artifact,
    assess_legacy_artifact_file,
)
from paperworks.contracts.models import (
    LegacyFieldMapping,
    LegacyMigrationAssessment,
    SchemaRegistration,
    StructuralValidationIssue,
    StructuralValidationReport,
)
from paperworks.contracts.schema_registry import (
    SchemaRegistry,
    SchemaRegistryError,
    load_schema_registry,
    validate_artifact,
    validate_artifact_file,
)
from paperworks.contracts.rule_v1 import (
    AbstentionPolicySpec,
    ComplexitySpec,
    DelayedResponseRuleV1,
    ExpectedEffectSpec,
    LagSpec,
    OperatingRegimeSpec,
    OutputSemanticsSpec,
    PersistenceSpec,
    ReviewHistoryEntry,
    RuleProvenanceSpec,
    RuleV1ModelError,
    SeverityPolicySpec,
    TriggerSpec,
    WindowSpec,
    canonical_rule_document_bytes,
    canonical_rule_document_sha256,
    delayed_response_rule_to_dict,
    load_delayed_response_rule,
    parse_delayed_response_rule,
    serialize_delayed_response_rule,
)

__all__ = [
    "ADAPTER_VERSION",
    "AbstentionPolicySpec",
    "ComplexitySpec",
    "DelayedResponseRuleV1",
    "ExpectedEffectSpec",
    "LagSpec",
    "LegacyFieldMapping",
    "LegacyMigrationAssessment",
    "OperatingRegimeSpec",
    "OutputSemanticsSpec",
    "PersistenceSpec",
    "ReviewHistoryEntry",
    "RuleProvenanceSpec",
    "RuleV1ModelError",
    "SchemaRegistration",
    "SchemaRegistry",
    "SchemaRegistryError",
    "StructuralValidationIssue",
    "StructuralValidationReport",
    "SeverityPolicySpec",
    "TriggerSpec",
    "WindowSpec",
    "assess_legacy_artifact",
    "assess_legacy_artifact_file",
    "canonical_rule_document_bytes",
    "canonical_rule_document_sha256",
    "delayed_response_rule_to_dict",
    "load_delayed_response_rule",
    "load_schema_registry",
    "parse_delayed_response_rule",
    "serialize_delayed_response_rule",
    "validate_artifact",
    "validate_artifact_file",
]
