"""Freeze the post-DEC-037 pre-access DAG and narrow source blocker."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
def cb(v):return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=True).encode()
def d(v):return hashlib.sha256(cb(v)).hexdigest()
def sh(v):return {**v,'self_hash':d(v)}
def l(p):return json.loads(p.read_text())
def main():
 p=argparse.ArgumentParser();p.add_argument('--dir',type=Path,required=True);a=p.parse_args();q=a.dir;d37=l(q/'DEC037_HAI21_PROSPECTIVE_DIRECT_TARGET_PROCESS_SCOPE_AMENDMENT_V1.json');h21=l(q/'HAI21_P1_DIRECT_TARGET_ELIGIBILITY_AUTHORITY_V2.json');h22=l(q/'HAI22_P1_DIRECT_TARGET_ELIGIBILITY_AUTHORITY_V2.json');r22=l(q/'HAI22_DEC036_SIX_CASE_OFFICIAL_SOURCE_RECOVERY_V1.json');u=l(q/'HAI_OFFICIAL_SOURCE_TRIANGULATED_SCENARIO_AUTHORITY_V1.json')
 dag=sh({'schema':'dg05_dec037_p1_source_recovery_authority_dag_v1','status':'MAXIMUM_SAFE_PROGRESS_COMPLETE_BLOCKED','nodes':{'HAI23_SCENARIO':'FROZEN','HAI23_P1_DEC034':'PASS','HAI22_SCENARIO':'FROZEN','HAI22_P1_DEC036':'BLOCKED_SOURCE_AUTHORITY','HAI21_SCENARIO_DEC035':'FROZEN','HAI21_P1_DEC037':'PASS','UNIFIED_146_SCENARIO':'PASS','UNIFIED_P1':'BLOCKED_HAI22_SOURCE_AUTHORITY','SCENARIO_ADAPTER_V11':'COMPONENT_AUDITED_NOT_PROMOTED','LABEL_CUSTODIAN_V11':'NOT_RUN','PRODUCTION_ROUTE_V11':'NOT_RUN','KERNEL_PARITY':'NOT_RUN','RAW_ROOT_LINEAGE':'SCENARIO_AND_HAI21_P1_ROOTS_PASS','INDEPENDENT_QA':'PARTIAL','PRIVACY_QA':'PASS_FOCUSED','V11_CANDIDATE':'NOT_CREATED','EXACT_USER_APPROVAL':'NOT_RUN','DG05_REAL_EXECUTION':'NOT_RUN'},'roots':{'DEC037':d37['self_hash'],'HAI21_ELIGIBILITY':h21['eligibility_authority_sha256'],'HAI22_ELIGIBILITY':h22['eligibility_authority_sha256'],'HAI22_RECOVERY':r22['self_hash'],'UNIFIED_SCENARIO':u['private_authority_sha256']},'performance_contact':{'heldout_feature_values_used_for_method_design':0,'heldout_predictions_observed':0,'heldout_metrics_observed':0,'method_comparisons_observed':0,'result_driven_changes':0}});(q/'DG05_DEC037_P1_SOURCE_RECOVERY_AUTHORITY_DAG_V1.json').write_bytes(cb(dag)+b'\n')
 text='''# DG-05 DEC-037 P1 source-recovery handoff\n\nHAI21 DEC-037 has closed its P1 authority: 34 eligible, 16 not eligible, 0 unresolved. HAI22 DEC-036 remains incomplete: one raw direct-target representation is row-bound to multiple official controller processes and affects six scenarios. Official HAI22-compatible sources examined do not supply a unique process ownership; no alias, target splitting, or cross-version graph reuse was applied.\n\nThe 146-scenario authority remains frozen and unchanged. The post-freeze scenario adapter component remains audited, but V11 custodian/route promotion and an executable candidate are fail-closed pending the HAI22 source-root resolution. No held-out prediction, metric, comparison, or result exists.\n\nExact next: obtain official HAI22 identifier/controller topology that uniquely establishes this target’s physical process, or obtain a user decision only if a new semantic treatment is necessary.\n''';(q/'DG05_DEC037_P1_SOURCE_RECOVERY_HANDOFF_V1.md').write_text(text,encoding='utf-8');print(json.dumps({'dag':dag['self_hash']},sort_keys=True))
if __name__=='__main__':main()
